- name: test
  ansible.builtin.debug:
    msg: hello from frontend
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed
  register: out

- name: out
  debug:
    msg: "{{out}}"
