- name: install python deps
  ansible.builtin.yum:
     name:
        - python3-pymysql
        - mysql
     state: installed

- name: load mysql schema
  community.mysql.mysql_db:
     state: import
     name: all
     target: /app/schema/{{component}}.sql
     login_host: mysql-dev.devops009.online
     login-user: root
     login_password: "{{root_mysql_password"