- name: Install python 3
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-deve1
    state: installed

- name: App Pre-reg
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: download python dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6

- name: systemD setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: load schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load
